-- 코드를 입력하세요
SELECT T.FOOD_TYPE, T.REST_ID, T.REST_NAME, T.FAVORITES
FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS NUM FROM REST_INFO) T
WHERE T.NUM=1
ORDER BY FOOD_TYPE DESC;