-- 코드를 입력하세요
WITH TOTAL AS(
    SELECT * FROM USER_INFO
    WHERE YEAR(JOINED)=2021
)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID)/COUNT(DISTINCT TOTAL.USER_ID), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE, TOTAL
WHERE EXISTS (SELECT 1 FROM USER_INFO WHERE YEAR(JOINED)=2021 AND ONLINE_SALE.USER_ID = USER_INFO.USER_ID)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;