-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME 
FROM (
        SELECT CATEGORY, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK, PRICE, PRODUCT_NAME 
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('식용유','과자','국','김치')
    ) T
WHERE RNK=1
ORDER BY MAX_PRICE DESC
;